name: Release

on:
  push:
    tags:
      - 'v*'

permissions: read-all

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: Set up Go 1.25.7
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version: 1.25.7
      
      - name: Get the version
        id: tag
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Login docker
        run: echo "$GITHUB_ACCESS_TOKEN" | docker login ghcr.io -u wquintal --password-stdin
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      
      - name: Docker build
        run: docker build -t ghcr.io/bascanada/logviewer:${VERSION} .
        env:
          VERSION: ${{ steps.tag.outputs.tag }}
      
      - name: Docker push
        run: docker push ghcr.io/bascanada/logviewer:${VERSION}
        env:
          VERSION: ${{ steps.tag.outputs.tag }}

      - name: Install cosign
        uses: sigstore/cosign-installer@faadad0cce49287aee09b3a48701e75088a2c6ad # v4.0.0

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@1a80836c5c9d9e5755a25cb59ec6f45a3b5f41a8 # v7.2.1
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAP_GITHUB_TOKEN: ${{ secrets.TAP_GITHUB_TOKEN }}
          AUR_KEY: ${{ secrets.AUR_KEY }}
